Deep Learning:
    ALAD:
        activation_hidden_disc: tanh
        activation_hidden_gen: tanh
        add_disc_zz_loss: true
        add_recon_loss: false
        batch_size: 32
        contamination: 0.1
        dec_layers:
        - 5
        - 10
        - 25
        device: null
        disc_xx_layers:
        - 25
        - 10
        - 5
        disc_xz_layers:
        - 25
        - 10
        - 5
        disc_zz_layers:
        - 25
        - 10
        - 5
        dropout_rate: 0.2
        enc_layers:
        - 25
        - 10
        - 5
        epochs: 200
        lambda_recon_loss: 0.1
        latent_dim: 2
        learning_rate_disc: 0.0001
        learning_rate_gen: 0.0001
        output_activation: null
        preprocessing: false
        spectral_normalization: false
        verbose: 0
    AnoGAN:
        D_layers:
        - 20
        - 10
        - 5
        G_layers:
        - 20
        - 10
        - 3
        - 10
        - 20
        activation_hidden: tanh
        batch_size: 32
        contamination: 0.1
        device: null
        dropout_rate: 0.2
        epochs: 500
        epochs_query: 20
        index_D_layer_for_recon_error: 1
        latent_dim_G: 2
        learning_rate: 0.001
        learning_rate_query: 0.01
        output_activation: null
        preprocessing: false
        verbose: 0
    AutoEncoder:
        batch_norm: true
        batch_size: 32
        compile_mode: default
        contamination: 0.1
        device: null
        dropout_rate: 0.2
        epoch_num: 10
        hidden_activation_name: relu
        hidden_neuron_list:
        - 64
        - 32
        lr: 0.001
        optimizer_name: adam
        optimizer_params:
            weight_decay: 1.0e-05
        preprocessing: true
        random_state: 42
        use_compile: false
        verbose: 1
    DeepSVDD:
        batch_size: 32
        c: null
        contamination: 0.1
        dropout_rate: 0.2
        epochs: 100
        hidden_activation: relu
        hidden_neurons: null
        l2_regularizer: 0.1
        n_features: empty
        optimizer: adam
        output_activation: sigmoid
        preprocessing: true
        random_state: null
        use_ae: false
        validation_size: 0.1
        verbose: 1
    MO_GAAL:
        contamination: 0.1
        k: 10
        lr_d: 0.01
        lr_g: 0.0001
        momentum: 0.9
        stop_epochs: 20
    SO_GAAL:
        contamination: 0.1
        lr_d: 0.01
        lr_g: 0.0001
        momentum: 0.9
        stop_epochs: 20
    VAE:
        batch_norm: false
        batch_size: 32
        beta: 1.0
        capacity: 0.0
        compile_mode: default
        contamination: 0.1
        decoder_neuron_list:
        - 32
        - 64
        - 128
        device: null
        dropout_rate: 0.2
        encoder_neuron_list:
        - 128
        - 64
        - 32
        epoch_num: 30
        hidden_activation_name: relu
        latent_dim: 2
        lr: 0.001
        optimizer_name: adam
        optimizer_params:
            weight_decay: 1.0e-05
        output_activation_name: sigmoid
        preprocessing: true
        random_state: 42
        use_compile: false
        verbose: 1
Machine Learning:
    DecisionTreeClassifier:
        ccp_alpha: 0.0
        class_weight: null
        criterion: gini
        max_depth: null
        max_features: null
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        random_state: null
        splitter: best
    ECOD:
        contamination: 0.1
        n_jobs: 1
    GaussianNB:
        priors: null
        var_smoothing: 1.0e-09
    IForest:
        behaviour: old
        bootstrap: false
        contamination: 0.1
        max_features: 1.0
        max_samples: auto
        n_estimators: 100
        n_jobs: 1
        random_state: null
        verbose: 0
    KNN:
        algorithm: auto
        contamination: 0.1
        leaf_size: 30
        method: largest
        metric: minkowski
        metric_params: null
        n_jobs: 1
        n_neighbors: 5
        p: 2
        radius: 1.0
    LOF:
        algorithm: auto
        contamination: 0.1
        leaf_size: 30
        metric: minkowski
        metric_params: null
        n_jobs: 1
        n_neighbors: 20
        novelty: true
        p: 2
    MLPClassifier:
        activation: relu
        alpha: 0.0001
        batch_size: auto
        beta_1: 0.9
        beta_2: 0.999
        early_stopping: false
        epsilon: 1.0e-08
        hidden_layer_sizes:
        - 100
        learning_rate: constant
        learning_rate_init: 0.001
        max_fun: 15000
        max_iter: 200
        momentum: 0.9
        n_iter_no_change: 10
        nesterovs_momentum: true
        power_t: 0.5
        random_state: null
        shuffle: true
        solver: adam
        tol: 0.0001
        validation_fraction: 0.1
        verbose: false
        warm_start: false
    MultinomialNB:
        alpha: 1.0
        class_prior: null
        fit_prior: true
        force_alpha: warn
    OCSVM:
        cache_size: 200
        coef0: 0.0
        contamination: 0.1
        degree: 3
        gamma: auto
        kernel: rbf
        max_iter: -1
        nu: 0.5
        shrinking: true
        tol: 0.001
        verbose: false
    RandomForestClassifier:
        bootstrap: true
        ccp_alpha: 0.0
        class_weight: null
        criterion: gini
        max_depth: null
        max_features: sqrt
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: null
        verbose: 0
        warm_start: false
    SVM:
        C: 1.0
        break_ties: false
        cache_size: 200
        class_weight: null
        coef0: 0.0
        decision_function_shape: ovr
        degree: 3
        gamma: scale
        kernel: rbf
        max_iter: -1
        probability: false
        random_state: null
        shrinking: true
        tol: 0.001
        verbose: false
Statistical:
    ABOD:
        contamination: 0.1
        method: fast
        n_neighbors: 5
    ARIMA:
        concentrate_scale: false
        dates: null
        endog:
        - 1
        - 2
        enforce_invertibility: true
        enforce_stationarity: true
        exog: null
        freq: null
        missing: none
        order:
        - 0
        - 0
        - 0
        seasonal_order:
        - 0
        - 0
        - 0
        - 0
        trend: null
        trend_offset: 1
        validate_specification: true
    CBLOF:
        alpha: 0.9
        beta: 5
        check_estimator: false
        clustering_estimator: null
        contamination: 0.1
        n_clusters: 8
        n_jobs: 1
        random_state: null
        use_weights: false
    CD:
        contamination: 0.1
        model:
            __model__: LinearRegression
            __module__: sklearn.linear_model._base
            params:
                copy_X: true
                fit_intercept: true
                n_jobs: null
                positive: false
    COF:
        contamination: 0.1
        method: fast
        n_neighbors: 20
    COPOD:
        contamination: 0.1
        n_jobs: 1
    FeatureBagging:
        base_estimator: null
        bootstrap_features: false
        check_detector: true
        check_estimator: false
        combination: average
        contamination: 0.1
        estimator_params: null
        max_features: 1.0
        n_estimators: 10
        n_jobs: 1
        random_state: null
        verbose: 0
    GMM:
        contamination: 0.1
        covariance_type: full
        init_params: kmeans
        max_iter: 100
        means_init: null
        n_components: 1
        n_init: 1
        precisions_init: null
        random_state: null
        reg_covar: 1.0e-06
        tol: 0.001
        warm_start: false
        weights_init: null
    HBOS:
        alpha: 0.1
        contamination: 0.1
        n_bins: 10
        tol: 0.5
    HoltWinters:
        damped_trend: false
        endog:
        - 1
        - 2
        exponential: false
        initial_level: null
        initial_trend: null
        initialization_method: null
    INNE:
        contamination: 0.1
        max_samples: auto
        n_estimators: 200
        random_state: null
    KDE:
        algorithm: auto
        bandwidth: 1.0
        contamination: 0.1
        leaf_size: 30
        metric: minkowski
        metric_params: null
    KPCA:
        alpha: 1.0
        coef0: 1
        contamination: 0.1
        copy_X: true
        degree: 3
        eigen_solver: auto
        gamma: null
        kernel: rbf
        kernel_params: null
        max_iter: null
        n_components: null
        n_jobs: null
        n_selected_components: null
        random_state: null
        remove_zero_eig: false
        sampling: false
        subset_size: 20
        tol: 0
    LMDD:
        contamination: 0.1
        dis_measure: aad
        n_iter: 50
        random_state: null
    LOCI:
        alpha: 0.5
        contamination: 0.1
        k: 3
    LODA:
        contamination: 0.1
        n_bins: 10
        n_random_cuts: 100
    LSCP:
        contamination: 0.1
        detector_list:
        -   __model__: LOF
            __module__: pyod.models.lof
            params:
                algorithm: auto
                contamination: 0.1
                leaf_size: 30
                metric: minkowski
                metric_params: null
                n_jobs: 1
                n_neighbors: 20
                novelty: true
                p: 2
        local_max_features: 1.0
        local_region_size: 30
        n_bins: 10
        random_state: null
    LUNAR:
        contamination: 0.1
        epsilon: 0.1
        lr: 0.001
        model_type: WEIGHT
        n_epochs: 200
        n_neighbours: 5
        negative_sampling: MIXED
        proportion: 1.0
        scaler:
            __model__: MinMaxScaler
            __module__: sklearn.preprocessing._data
            params:
                clip: false
                copy: true
                feature_range:
                - 0
                - 1
        val_size: 0.1
        verbose: 0
        wd: 0.1
    MAD:
        contamination: 0.1
        threshold: 3.5
    MCD:
        assume_centered: false
        contamination: 0.1
        random_state: null
        store_precision: true
        support_fraction: null
    MatrixProfile:
        T:
        - 1
        - 2
        T_subseq_isconstant: null
        discords: false
        include: null
        m: empty
        normalize: true
        p: 2.0
    PCA:
        contamination: 0.1
        copy: true
        iterated_power: auto
        n_components: null
        n_selected_components: null
        random_state: null
        standardization: true
        svd_solver: auto
        tol: 0.0
        weighted: true
        whiten: false
    QMCD:
        contamination: 0.1
    RGraph:
        active_support: true
        algorithm: lasso_lars
        blocksize_test_data: 10
        contamination: 0.1
        fit_intercept_LR: false
        gamma: 50.0
        gamma_nz: true
        maxiter: 40
        maxiter_lasso: 1000
        n_nonzero: 10
        preprocessing: true
        support_init: L2
        support_size: 100
        tau: 1.0
        transition_steps: 10
        verbose: true
    ROD:
        contamination: 0.1
        parallel_execution: false
    SARIMAX:
        concentrate_scale: false
        dates: null
        endog:
        - 1
        - 2
        enforce_invertibility: true
        enforce_stationarity: true
        exog: null
        freq: null
        hamilton_representation: false
        measurement_error: false
        missing: none
        mle_regression: true
        order:
        - 1
        - 0
        - 0
        seasonal_order:
        - 0
        - 0
        - 0
        - 0
        simple_differencing: false
        time_varying_regression: false
        trend: null
        trend_offset: 1
        use_exact_diffuse: false
        validate_specification: true
    SOD:
        alpha: 0.8
        contamination: 0.1
        n_neighbors: 20
        ref_set: 10
    SOS:
        contamination: 0.1
        eps: 1.0e-05
        metric: euclidean
        perplexity: 4.5
    Sampling:
        contamination: 0.1
        metric: minkowski
        metric_params: null
        random_state: null
        subset_size: 20
    SingleExponentialSmoothing:
        bounds: null
        damped_trend: false
        dates: null
        endog:
        - 1
        - 2
        error: add
        freq: null
        initial_level: null
        initial_seasonal: null
        initial_trend: null
        initialization_method: estimated
        missing: none
        seasonal: null
        seasonal_periods: null
        trend: null
    VARMAX:
        endog:
        -   - 1
        -   - 2
        enforce_invertibility: true
        enforce_stationarity: true
        error_cov_type: unstructured
        exog: null
        measurement_error: false
        order:
        - 1
        - 0
        trend: c
        trend_offset: 1
    XGBOD:
        base_score: 0.5
        booster: gbtree
        colsample_bylevel: 1
        colsample_bytree: 1
        estimator_list: null
        gamma: 0
        learning_rate: 0.1
        max_delta_step: 0
        max_depth: 3
        min_child_weight: 1
        n_estimators: 100
        n_jobs: 1
        nthread: null
        objective: binary:logistic
        random_state: 0
        reg_alpha: 0
        reg_lambda: 1
        scale_pos_weight: 1
        silent: true
        standardization_flag_list: null
        subsample: 1
